In [166]:
import pandas as pd
import matplotlib.pyplot as plt

In [167]:
df=pd.read_csv("survey_results_public.csv")

In [168]:
df.head()

Respondent                                         MainBranch Hobbyist  \
0           1                     I am a developer by profession      Yes   
1           2                     I am a developer by profession       No   
2           3                        I code primarily as a hobby      Yes   
3           4                     I am a developer by profession      Yes   
4           5  I used to be a developer by profession, but no...      Yes   

    Age Age1stCode CompFreq  CompTotal  ConvertedComp             Country  \
0   NaN         13  Monthly        NaN            NaN             Germany   
1   NaN         19      NaN        NaN            NaN      United Kingdom   
2   NaN         15      NaN        NaN            NaN  Russian Federation   
3  25.0         18      NaN        NaN            NaN             Albania   
4  31.0         16      NaN        NaN            NaN       United States   

     CurrencyDesc  ...                  SurveyEase           SurveyLength  \
0   European Euro  ...  Neither easy nor difficult  Appropriate in length   
1  Pound sterling  ...                         NaN                    NaN   
2             NaN  ...  Neither easy nor difficult  Appropriate in length   
3    Albanian lek  ...                         NaN                    NaN   
4             NaN  ...                        Easy              Too short   

  Trans                                     UndergradMajor  \
0    No  Computer science, computer engineering, or sof...   
1   NaN  Computer science, computer engineering, or sof...   
2   NaN                                                NaN   
3    No  Computer science, computer engineering, or sof...   
4    No  Computer science, computer engineering, or sof...   

  WebframeDesireNextYear    WebframeWorkedWith  \
0           ASP.NET Core  ASP.NET;ASP.NET Core   
1                    NaN                   NaN   
2                    NaN                   NaN   
3                    NaN                   NaN   
4   Django;Ruby on Rails         Ruby on Rails   

                              WelcomeChange WorkWeekHrs YearsCode YearsCodePro  
0   Just as welcome now as I felt last year        50.0        36           27  
1  Somewhat more welcome now than last year         NaN         7            4  
2  Somewhat more welcome now than last year         NaN         4          NaN  
3  Somewhat less welcome now than last year        40.0         7            4  
4   Just as welcome now as I felt last year         NaN        15            8  

[5 rows x 61 columns]

In [169]:
df = df[["Country","EdLevel","YearsCodePro","Employment","ConvertedComp"]]

In [170]:
df=df.rename({"ConvertedComp":"Salary"},axis=1)

In [171]:
df.head()

Country                                          EdLevel  \
0             Germany  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
1      United Kingdom     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
2  Russian Federation                                              NaN   
3             Albania  Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
4       United States     Bachelor’s degree (B.A., B.S., B.Eng., etc.)   

  YearsCodePro                                         Employment  Salary  
0           27  Independent contractor, freelancer, or self-em...     NaN  
1            4                                 Employed full-time     NaN  
2          NaN                                                NaN     NaN  
3            4                                                NaN     NaN  
4            8                                 Employed full-time     NaN

In [172]:
df=df[df["Salary"].notnull()]

In [173]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34756 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34756 non-null  object 
 1   EdLevel       34188 non-null  object 
 2   YearsCodePro  34621 non-null  object 
 3   Employment    34717 non-null  object 
 4   Salary        34756 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [174]:
df=df.dropna()
df.isnull().sum()
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34025 entries, 7 to 64154
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       34025 non-null  object 
 1   EdLevel       34025 non-null  object 
 2   YearsCodePro  34025 non-null  object 
 3   Employment    34025 non-null  object 
 4   Salary        34025 non-null  float64
dtypes: float64(1), object(4)
memory usage: 1.6+ MB


In [175]:
df=df[df["Employment"]=="Employed full-time"]


In [176]:
df=df.drop("Employment",axis=1)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30019 entries, 7 to 64154
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Country       30019 non-null  object 
 1   EdLevel       30019 non-null  object 
 2   YearsCodePro  30019 non-null  object 
 3   Salary        30019 non-null  float64
dtypes: float64(1), object(3)
memory usage: 1.1+ MB


In [177]:
df['Country'].value_counts()

Country
United States     7569
India             2425
United Kingdom    2287
Germany           1903
Canada            1178
                  ... 
Benin                1
Fiji                 1
San Marino           1
Guinea               1
Andorra              1
Name: count, Length: 154, dtype: int64

In [178]:
def shorten_categories(categories, cutoff):
    categorical_map={}
    for i in range (len(categories)):
        if categories.values[i] >= cutoff:
            categorical_map[categories.index[i]]=categories.index[i]
        else:
            categorical_map[categories.index[i]]='other'
    return categorical_map
        


    

In [179]:
cat_map=shorten_categories(df.Country.value_counts(),400)
df['Country']=df['Country'].map(cat_map)
df.Country.value_counts()

Country
other                 8549
United States         7569
India                 2425
United Kingdom        2287
Germany               1903
Canada                1178
Brazil                 991
France                 972
Spain                  670
Australia              659
Netherlands            654
Poland                 566
Italy                  560
Russian Federation     522
Sweden                 514
Name: count, dtype: int64

In [180]:
df.head()

Country                                            EdLevel  \
7    United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
11           Spain  Some college/university study without earning ...   
12     Netherlands  Secondary school (e.g. American high school, G...   

   YearsCodePro    Salary  
7            13  116000.0  
9             4   32315.0  
10            2   40070.0  
11            7   14268.0  
12           20   38916.0

In [181]:
df=df[df["Salary"]<=250000]
df=df[df["Salary"]>=10000]
df=df[df["Country"]!="other"]

In [182]:
df.head()

Country                                            EdLevel  \
7    United States       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
9   United Kingdom    Master’s degree (M.A., M.S., M.Eng., MBA, etc.)   
10  United Kingdom       Bachelor’s degree (B.A., B.S., B.Eng., etc.)   
11           Spain  Some college/university study without earning ...   
12     Netherlands  Secondary school (e.g. American high school, G...   

   YearsCodePro    Salary  
7            13  116000.0  
9             4   32315.0  
10            2   40070.0  
11            7   14268.0  
12           20   38916.0

In [183]:
df["YearsCodePro"].unique()

array(['13', '4', '2', '7', '20', '1', '3', '10', '12', '29', '6', '28',
       '8', '23', '15', '25', '9', '11', 'Less than 1 year', '5', '21',
       '16', '18', '14', '32', '19', '22', '38', '30', '26', '27', '17',
       '24', '34', '35', '33', '36', '40', '39', 'More than 50 years',
       '31', '37', '41', '45', '42', '44', '43', '50', '49'], dtype=object)

In [184]:
def changeExp(yearsExp):
    if yearsExp =='Less than 1 year':
        return 0.5
    if yearsExp == 'More than 50 years':
        return 50
    return float(yearsExp)

df["YearsCodePro"]=df["YearsCodePro"].apply(changeExp)
     


In [185]:
df["YearsCodePro"].unique()

array([13. ,  4. ,  2. ,  7. , 20. ,  1. ,  3. , 10. , 12. , 29. ,  6. ,
       28. ,  8. , 23. , 15. , 25. ,  9. , 11. ,  0.5,  5. , 21. , 16. ,
       18. , 14. , 32. , 19. , 22. , 38. , 30. , 26. , 27. , 17. , 24. ,
       34. , 35. , 33. , 36. , 40. , 39. , 50. , 31. , 37. , 41. , 45. ,
       42. , 44. , 43. , 49. ])

In [186]:
df["EdLevel"].unique()

array(['Bachelor’s degree (B.A., B.S., B.Eng., etc.)',
       'Master’s degree (M.A., M.S., M.Eng., MBA, etc.)',
       'Some college/university study without earning a degree',
       'Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)',
       'Associate degree (A.A., A.S., etc.)',
       'Professional degree (JD, MD, etc.)',
       'Other doctoral degree (Ph.D., Ed.D., etc.)',
       'I never completed any formal education',
       'Primary/elementary school'], dtype=object)

In [187]:
def changeEdu(x):
    if 'B.A.' in x:
        return 'Bachelors degree'
    if 'M.A.' in x:
        return 'Masters degree'
    if 'Professional degree' in x or 'Other doctoral' in x:
        return 'Post Graduation'
    return 'Less than a Bachelors'

df['EdLevel']=df['EdLevel'].apply(changeEdu)

In [188]:
df["EdLevel"].unique()

array(['Bachelors degree', 'Masters degree', 'Less than a Bachelors',
       'Post Graduation'], dtype=object)

In [189]:
from sklearn.preprocessing import LabelEncoder
Ed_enc=LabelEncoder()
df["EdLevel"]=Ed_enc.fit_transform(df['EdLevel'])
df['EdLevel'].unique()

array([0, 2, 1, 3])

In [190]:
Co_enc=LabelEncoder()
df["Country"]=Co_enc.fit_transform(df['Country'])
df['Country'].unique()

array([13, 12, 10,  7,  4,  2,  6,  1,  3,  5, 11,  8,  0,  9])

In [191]:
x=df[['Country','EdLevel','YearsCodePro']]
#x=df.drop("Salary",axis=1)
y=df["Salary"]


In [192]:
from sklearn.linear_model import LinearRegression
linear_reg=LinearRegression()
linear_reg.fit(x,y.values)

LinearRegression()

In [193]:
y_pred=linear_reg.predict(x)

In [194]:
from sklearn.metrics import mean_squared_error, mean_absolute_error
import numpy as np
error=np.sqrt(mean_squared_error(y,y_pred))

In [195]:
error

39274.75368318509

In [196]:
x

Country  EdLevel  YearsCodePro
7           13        0          13.0
9           12        2           4.0
10          12        0           2.0
11          10        1           7.0
12           7        1          20.0
...        ...      ...           ...
64113       13        1          15.0
64116       13        0           6.0
64122       13        1           4.0
64127       13        3          12.0
64129       13        2           4.0

[18491 rows x 3 columns]

In [197]:
x=np.array([["United States",'Masters degree',15]])
x

array([['United States', 'Masters degree', '15']], dtype='<U21')

In [198]:
x[:,0] =Co_enc.transform(x[:,0])
x[:,1] =Ed_enc.transform(x[:,1])
x=x.astype(float)
x


array([[13.,  2., 15.]])

In [199]:
y_predict=linear_reg.predict(x)
y_predict

/opt/anaconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([108641.10866557])

In [201]:
import pickle

In [202]:

data={"model":linear_reg,"Co_enc":Co_enc,"Ed_enc":Ed_enc}
with open('save_steps.pkl','wb') as file:
    pickle.dump(data,file)

In [204]:
with open('save_steps.pkl','rb') as file:
    data=pickle.load(file)
model=data["model"]

In [205]:
y_pred=model.predict(x)
y_pred

/opt/anaconda3/envs/ml/lib/python3.9/site-packages/sklearn/base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([108641.10866557])